### ISSUE TITLE
Can't install on Firefox

### ISSUE THREAD

**Issue by marcbelmont** [emadehsan/marsjs#2]
Extensions for Firefox are built using the WebExtensions API, a cross-browser system for developing extensions. The extension should work on Firefox too. Please publish on the Firefox Add-ons site.

**Comment by emadehsan** [comment]
Hey Marc, thank you for your suggestion!

Can you please help with this? :)

**Comment by emadehsan** [comment]
If publishing to Firefox Add-ons site is the only task, consider it done. I would test on Firefox and publish there.

**Comment by marcbelmont** [comment]
I'll be happy to test the extension once it's online.

**Comment by emadehsan** [comment]
Hi Marc, I've tested now. Extension works perfectly in Firefox when loaded as temporary add-on. I've added instructions on usage in Firefox in the README. Didn't know it would be so simple to make it work in Firefox. Thank you for informing :) 👍 . Publishing to Firefox add-ons site

**Comment by emadehsan** [comment]
Firefox Add-on has been published: https://addons.mozilla.org/en-GB/firefox/addon/marsathome/

**Comment by marcbelmont** [comment]
Awesome. Thanks!
